### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by suhr** [harrisonvanderbyl/rwkv_chatbot#3]
```
[suhr@nixos:~/rwkv_chatbot]$ python ./processPrompts.py 
[?] What model do you want to use?: RWKV-4-Pile-3B-Instruct-test1-20230124.pth
 > RWKV-4-Pile-3B-Instruct-test1-20230124.pth

[?] What inference backend do you want to use?: pytorch-stream(gpu-config-vram)
   tensorflow(cpu/gpu)
   pytorch(cpu/gpu)
   numpy(cpu)
   jax(cpu/gpu/tpu)
   pytorch-deepspeed(gpu)
   pytorch-quant(gpu-8bit)
 > pytorch-stream(gpu-config-vram)
   pytorch-split(2xgpu)
   export-torchscript
   export-tensorflow
   pytorch-compatibility(cpu/debug)

init RWKVOPS, from super
[?] Pin memory to cpu? (Y/n): 
Designate the amount of memory to allocate (in GB):16
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 582/582 [00:05<00:00, 102.96it/s]
Traceback (most recent call last):
  File "/home/suhr/rwkv_chatbot/./processPrompts.py", line 11, in <module>
    jsonl = [json.loads(line)["question"] for line in jsonl]
  File "/home/suhr/rwkv_chatbot/./processPrompts.py", line 11, in <listcomp>
    jsonl = [json.loads(line)["question"] for line in jsonl]
  File "/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Tried in NixOS with the following environment: https://github.com/suhr/rwkv_chatbot/blob/flake/flake.nix

**Comment by harrisonvanderbyl** [comment]
Hi! Apologies, the processPrompts.py file is a file for doing batch generation. If you are looking for a discord chatbot or a webui, please use multi.py, or if you just want to check out the model, use the .ipynb file code, or make yourself something based off of example.py

**Comment by harrisonvanderbyl** [comment]
runOptimized.py is good for testing speed

**Comment by suhr** [comment]
`multi.py` just silently terminates, that's why I decided to try `./processPrompts.py`.

**Comment by suhr** [comment]
But `example.py` works fine, so the problem is with the web server.

**Comment by harrisonvanderbyl** [comment]
Ammended error messages
